config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get('/', {to:'posts#index', as: 'root'})

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :edit, :update]
  get('/users/panel', {to: 'users#panel', as: 'users_panel'})
  get('/users/:id/edit_password', {to: 'users#edit_password', as: :edit_password})
  patch('/users/:id/update_password', {to: 'users#update_password', as: :update_password})

  resource :session, only: [:new, :create, :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action(:create,:read,:update,:delete, to: :crud )

    can(:crud, Post) do |post|
      user == post.user
    end

    can(:crud, Comment) do |comment|
      user == comment.user
    end

    can(:crud, User) do |user|
      user == user.user
    end

    if user.is_admin?
      can :manage, :all 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 50 }

    belongs_to :user
    
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :products, dependent: :nullify
    has_many :reviews, dependent: :nullify

    validates :email, presence: true, uniqueness: true

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, alert: "Please Sign In" unless user_signed_in?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_post, only:[:create, :destroy]

    def create
        @comment = Comment.new comment_params
        @comment.post = @post
        @comment.user = current_user
        if @comment.save
          redirect_to post_path(@post), notice: 'Comment created!'
        else
          render 'posts/show'
        end
      end
      def destroy
        @comment = Comment.find params[:id]
        @comment.destroy
        redirect_to post_path(@post), alert: 'Comment deleted!'
      end
    
    private
    def find_post
      @post = Post.find params[:post_id]
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except:[:index, :show]
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy]


    def index
        @posts = Post.all.order(created_at: :desc)
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new post_params
        @post.user = current_user
        if @post.save
            flash[:notice] = "Post created!"
            redirect_to posts_path
        else
            render :new
        end
    end

    def show
        @comment = Comment.new
        @comments = @post.comments.order(created_at: :desc)
    end
    
    def edit
    end

    def update
        if @post.update post_params
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        flash[:alert] = "Post deleted!"
        redirect_to posts_path
    end

    private
    def post_params
        params.require(:post).permit(:title, :body)
    end

    def find_post
        @post = Post.find params[:id]
    end

    def authorize_user!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @post)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        @user= User.find_by_email params[:email]
        if @user&.authenticate(params[:password])
            session[:user_id]=@user.id
            redirect_to root_path, notice: 'Logged in'
        else
            flash[:alert] = 'Incorrect email or password'
            render :new
        end
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:new, :create]
    def new
        @user=User.new
    end
    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Logged In!"
        else
            flash[:alert] = 'Cannot use an existing email!'
            render :new
        end
    end
    def edit
        @user = User.find_by_id params[:id]
    end
    def update
        @user = User.find_by_id params[:id]
        if @user.update user_params
            redirect_to root_path, notice: "User information updated"
        else 
            flash[:alert] = 'Cannot use an existing email!'
            render :edit
        end
    end
    def edit_password
        @user = User.find_by_id params[:id]
    end
    def update_password
        @user = current_user
        if params[:user][:password] == params[:user][:current_password]
            flash[:alert] = "Current and New Password cannot be the same!"
            render :edit_password
        elsif @user&.authenticate(params[:user][:current_password])
            if @user.update user_params 
                redirect_to edit_user_path, notice: "Password successfully updated!"
            else
                flash[:alert] = "New Password and Confirmation Password does not match!"
                render :edit_password
            end
        else 
            flash[:alert] = "Current Password is incorrect! Please try again"
            render :edit_password
        end    
    end
    def panel
    end
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div>
    <%= form_with(model:[@post, @comment], local:true) do |f| %>
    <% if @comment.errors.any? %>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %> 

    <br>
    <h3>Comment</h3>
    <div>
        <%= f.text_area(:body, cols: 75, rows:5, placeholder:`What's on your mind?`) %>
    </div>
    <%= f.submit "Comment", class: 'btn btn-outline-primary' %>
    <% end %>
</div>

app/views/layouts/_alerts.html.erb
<%if flash[:notice].present? %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice]  %> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
<% elsif flash[:alert].present? %> 
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%=  flash[:alert] %> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>

<% end %>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-light bg-light padding d-flex justify-content-between">
  <div>
    <a class="navbar-brand" href="/">Blog on Rails</a>
  </div>

  <div class="d-flex justify-content-around flex-row m-4">  
    <%= link_to 'Home', root_path %>
    <div class="ml-4">
      <%= link_to 'New Post', new_post_path %>
    </div>

    <% if user_signed_in?%>
    <div class="ml-4">
      Hello <%=link_to current_user.full_name, edit_user_path(current_user.id) %>!
    </div> 
    <div class="ml-4">
      <%= link_to 'Logout', session_path, method: :delete, data:{confirm: 'Are you sure you want to log out?'} %>
    </div>  
    <% else %>
    <div class="ml-4">
      <%= link_to 'Login', new_session_path  %>
    </div>
    <div class="ml-4">   
      <%= link_to 'Sign Up', new_user_path  %> 
    </div>  
    <% end %> 

    <% if current_user&.is_admin? %>
    <div class="ml-4">
      <%= link_to 'Admin Panel', users_panel_path %>  
    </div> 
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog On Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %> 
  <%= render 'layouts/alerts'%>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="padding">
    <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %> 
        <br>
        <div class="form-group">
            <%= f.label :title %>: <br>
            <%= f.text_area(:title, rows:2, cols:75) %>
        </div>
        <div class="form-group">
            <%= f.label :body %>: <br>
            <%= f.text_area(:body, rows:7, cols:75) %>
            
        </div>
        <br>
        <%= f.submit "Update Post", class: 'btn btn-outline-primary' %>
    <% end %>
</div>

app/views/posts/index.html.erb
<h1 class="padding">Post Index Page</h1>

<div class="padding row">
    <% @posts.each do |post| %>
        <div class="card col-md-4 rounded p-3 ">
            <h2><%= link_to post.title, post_path(post) %></h2>
            <p><%= post.body %></p>
            </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1 class = "padding">New Post</h1>
<div class="padding">
    <%= form_for @post do |f| %>   
    <% if @post.errors.any? %>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>   
        <div class="form-group">
            <%= f.label :title %>: <br>
            <%= f.text_area(:title, rows:2, cols:75) %>
        </div>
        <div class="form-group">
            <%= f.label :body %>: <br>
            <%= f.text_area(:body, rows:7, cols:75) %>
            
        </div>
        <br>
        <%= f.submit "Create Post", class: 'btn btn-outline-primary' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="padding">
    <h1><%= @post.title %></h1>
    <p><%= @post.body %></p>
    <h4>Created by: <%= @post.user&.full_name || 'DELETED'%></h4>
    <p>Posted: <%= time_ago_in_words(@post.created_at)%> ago</p>

    <% if can?(:crud, @post)%>
        <%= link_to '<button type="button" class="btn btn-outline-primary">Edit</button>'.html_safe, edit_post_path(@post) %>
        <%= link_to '<button type="button" class="btn btn-outline-primary">Delete</button>'.html_safe, post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %> 

    <%= render 'comments/form'%>
    <br> 
    <% @comments.each do |comment| %>
    <%= comment.body %> <br>
    <small>
        Commented: <%= time_ago_in_words(comment.created_at)%> ago | 
        <% if can? :crud, comment %>
            <%= link_to(" Delete", post_comment_path(@post, comment), method: :delete, data:{confirm: 'Are you sure?'})%> 
        <% end %>
    </small>
    <small> Commented by: <%= comment.user&.full_name || 'DELETED' %></small>
    <hr>

    <% end %>
</div>

app/views/users/edit.html.erb
<div class="padding">
    <h1>Update User Information</h1>
    <%= form_with model:@user, local: true do |f| %>
    <% if @user.errors.any? %>
        <p><%= @user.errors.full_messages.join(', ')%></p>
    <% end %>
    <br>
    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>
    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
    <br>
    <%= link_to "Edit Password", edit_password_path(current_user) %>
    <br> <br>
    <%= f.submit "Submit", class: 'btn btn-outline-primary' %>

    <% end %>
</div>

app/views/users/edit_password.html.erb
<div class="padding">
    <h1>Update User Password</h1>
    <%= form_with model:@user, url: update_password_path, local: true do |f| %>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <br>
    <div>
        <%= f.label :current_password %>
        <%= f.password_field :current_password %>
    </div>
    <div>
        <%= f.label :new_password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :new_password_confirmation %>
        <%= f.password_field :password_confirmation %> 
    </div>
    <br>
    <%= f.submit "Update Password", class: 'btn btn-outline-primary' %>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="padding">
    <h1>Sign Up</h1>
    <%= form_with model:@user, local: true do |f| %>
    <br>
    <% if @user.errors.any? %>
        <p><%= @user.errors.full_messages.join(', ')%></p>
    <% end %>
    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>
    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
    <br>
    <%= f.submit "Sign Up", class: 'btn btn-outline-primary' %>

    <% end %>
</div>

app/views/users/panel.html.erb
<div class="padding">
    <h1>Admin Panel</h1>
    <br>
    <p>The number of posts: <%= Post.count %></p>
    <p>The number of comments: <%= Comment.count %></p>
    <p>The number of users: <%= User.count %></p>
</div>